version: "3.9"
services:
  etcd:
    image: "quay.io/coreos/etcd:v3.4.1"
    command: [
      "etcd",
      "--name=etcd0",
      "--advertise-client-urls=http://10.5.0.3:2379,http://10.5.0.3:4001",
      "--listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001",
      "--initial-advertise-peer-urls=http://10.5.0.3:2380",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--initial-cluster-token=etcd-cluster-1",
      "--initial-cluster=etcd0=http://10.5.0.3:2380",
      "--initial-cluster-state=new"
    ]
    ports:
    - "2379:2379"
    - 2380
    - 4001
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  node_1:
    build: .
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    command: bash -c "CELIX_BUNDLES_PATH=/opt/maintec/build/deploy/maintec/bundles /opt/maintec/build/deploy/maintec/maintec"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1