version: "3.9"
services:
  gateway:
    build: .
    ports:
      - "6666:6666"
    command: bash -c "/opt/start_endpoint.sh"
  node_1:
    build: .
    ports:
      - "6667:6666"
    command: bash -c "/opt/start_maintec.sh"
