version: "3.9"
services:
  gateway:
    build: .
    ports:
      - "6666:6666"
    networks:
      default:
        ipv4_address: 192.168.1.3
  node_1:
    build: .
    ports:
      - "6667:6666"
    networks:
      default:
        ipv4_address: 192.168.1.4
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.1