version: "3.9"
services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  node_1:
    build: .
    ports:
    - "9999:9999"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    command: bash -c "RSA_IP=10.5.0.4 DISCOVERY_CFG_SERVER_IP=10.5.0.4 DISCOVERY_ETCD_SERVER_IP=10.5.0.3 CELIX_BUNDLES_PATH=/opt/maintec/build/deploy/maintec/bundles /opt/maintec/build/deploy/maintec/maintec"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1