version: "3.9"
services:
  endpoint:
    build: .
    ports:
      - "6666:6666"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    command: bash -c "CELIX_BUNDLES_PATH=/opt/maintec/build/deploy/endpoint/bundles /opt/maintec/build/deploy/endpoint/endpoint"
  node_1:
    build: .
    ports:
      - "6667:6666"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    command: bash -c "CELIX_BUNDLES_PATH=/opt/maintec/build/deploy/maintec/bundles /opt/maintec/build/deploy/maintec/maintec"


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1