version: "3.9"
services:
  configuration:
    build: bitnami/etcd
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  node_1:
    build: .
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    command: bash -c "CELIX_BUNDLES_PATH=/opt/maintec/build/deploy/maintec/bundles /opt/maintec/build/deploy/maintec/maintec"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1